### ISSUE TITLE
Translations to Polish language

### ISSUE THREAD

**Issue by Czech1932** [Maximoff/Apktool-M-translations#159]
Здравствуйте! Я хотел бы предложить добавить поддержку польского языка в ваше приложение. У меня уже есть готовый перевод, который, я уверен, поможет сделать ваше приложение доступным для большего числа пользователей. Буду очень признателен за ваше внимание к этому предложению. Спасибо!

**Comment by Maximoff** [comment]
да, добавьте ресурсы перевода в репозиторий. в ресурсы по умолчанию не нужно, выбор языка я сам добавлю.

**Comment by Maximoff** [comment]
отправьте мне файлы на почту, я добавлю их сам.
