### ISSUE TITLE
Wrong Language Title 

### ISSUE THREAD

**Issue by AgentHitmanFaris** [Maximoff/Apktool-M-translations#170]
I think you mistakenly thought my and in, In is for india and my for Malaysia, you have accidentally swapped for both language

**Comment by Maximoff** [comment]
"my" – [Myanmar](https://github.com/Maximoff/Apktool-M-translations/blob/56b75aa99eba43d0b6df13c79c555502580fbf0c/res/values/arrays.xml#L655), "in" – [Bahasa Indonesia](https://github.com/Maximoff/Apktool-M-translations/blob/56b75aa99eba43d0b6df13c79c555502580fbf0c/res/values/arrays.xml#L668). where did I go wrong?

**Comment by Maulana990** [comment]
> I think you mistakenly thought my and in, In is for india and my for Malaysia, you have accidentally swapped for both language

Look at this:
https://developer.android.com/guide/topics/resources/app-languages?hl=id#sample-config

**Comment by Maximoff** [comment]
> > I think you mistakenly thought my and in, In is for india and my for Malaysia, you have accidentally swapped for both language
> 
> Look at this: https://developer.android.com/guide/topics/resources/app-languages?hl=id#sample-config

Why should I look there? what is the problem?

**Comment by yimengqinyao** [comment]
> > > I think you mistakenly thought my and in, In is for india and my for Malaysia, you have accidentally swapped for both language
> > 
> > 
> > Look at this: https://developer.android.com/guide/topics/resources/app-languages?hl=id#sample-config
> 
> Why should I look there? what is the problem?

The link posted by this participant is for "AgentHitmanFaris", not for you. Ha ha!

**Comment by yimengqinyao** [comment]
> I think you mistakenly thought my and in, In is for india and my for Malaysia, you have accidentally swapped for both language

In the language abbreviation, "ms" is the Malay word that stands for Malaysia. "my" is a Burmese language.

**Comment by Maximoff** [comment]
короче, понятно
